#Minecraft server properties
#Sat Apr 04 23:43:31 UTC 2026
accepts-transfers=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=easy
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=lootr\:lootr_no_advancements,lootr\:lootr_no_suspicious_blocks
initial-enabled-packs=vanilla,fabric,accessories,badgebox,balm,beautify,berrypouch,carved_wood,cobble_contests,cobblecuisine,cobbled_counter,cobbledgacha,cobbledollars,cobblefurnies,cobblemon,cobblemon-additions,cobblemonalphas,cobblemonextrastructures,cobblemonintegrations,cobblemonraiddens,cobblemonresearchtasks,cobblenav,cobblepedia,cobbleversebadges,comforts,cozyhome,fabric-convention-tags-v2,fightorflight,ftbquests,handcrafted,journeymount,lenientdeath,libjf-data-v0,lootr,lootrmon,lumymon,mega_showdown,moarconcrete,mr_extra_eeveelutions,obc,patchouli,pokeblocks,porting_lib_item_abilities,rctmod,regions_unexplored,repurposed_structures,rgs,ribbits,sereneseasons,server_translations_api,simpletms,sophisticatedbackpacks,sophisticatedcore,sophisticatedstorage,structory,t_and_t,terrablender,terralith,tim_core,tmcraft,treechop,trinkets,visualworkbench,waystones,yungsapi,zamega,cobblemon\:repurposedstructurescobblemon,t_and_t\:resources/t_and_t_waystones_patch
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=180000
max-world-size=29999984
motd=§r              §5§l(MSX)  §dHosting Gratuito§r\n          §f§nhttps\://discord.gg/w9xt8ydNZe
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=6
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=6
white-list=false
